**Question 1. Create a 3x3 matrix with values ranging from 0 to 8 using numpy.**

In [ ]:
from numpy.lib.shape_base import array_split
import numpy as np
a=np.arange(0,9).reshape(3,3)
print(a)
# a=[0,1,2,3,4,5,6,7,8]
# arr=np.array(a).reshape(3,3)
# print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Question 2. Create a random vector of size 30 and find the mean, median and mode value using numpy.**

In [ ]:
import numpy as np
a=np.random.randint(10,size=30)
#a=np.random.random(30)
print('your vector',a)
print('mean:',np.mean(a))
print('median:',np.median(a))
print('mode:',np.max(a))

your vector [2 9 4 2 9 3 9 6 2 8 4 2 2 7 3 4 8 3 2 5 6 8 5 7 8 6 0 8 2 0]
mean: 4.8
median: 4.5
mode: 9



**Question 3.Create a 2d array with 0 on the border and 1 inside.**
 Ex- [[0,0,0,0],[0,1,1,0],[0,1,1,0],[0,0,0,0]]

In [ ]:
import numpy as np
# listx=[0,0,0,0,0,1,1,0,0,1,1,0,0,0,0,0]
# matx=np.array(listx).reshape(4,4)
# print(matx)
zero=np.zeros((4,4))
zero[1:-1,1:-1]=1
print(zero.astype('int64'))

[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


**Question 4. Create random vector of size 10 and replace the maximum value by 0.**
Ex:- [1,2,3,4,5] max value in this array is 5 then result would be [1,2,3,4,0]

In [ ]:
import numpy as np
a=np.random.randint(10,size=10)
#a=np.random.random(10)
print('old\n',a)
z=max(a)
a[a==z]=0
print('new\n',a)

**Question 5. Write a program to randomly place -1 in a 2D array p times. Here p means number of time element randomly placed**

Ex- if p=3 then in result array ,3 diffrent place should replace with -1 element.

In [ ]:
import numpy as np
a=3
b=3
matx=np.random.randint(9,size=(a,b))
print(f'main\n {matx}')
p=int(input('p='))

# M1
# a=np.random.randint(a,size=p)
# b=np.random.randint(b,size=p)
# count=0
# while count<p:
#   if matx[(a[count],b[count])]==-1:
#     continue
#   else:
#     matx[(a[count],b[count])]=-1
#     count=count+1
# print(f'after replacing\n {matx}')

# M2
i=0
while i<p:
  a=np.random.choice(a,size=1)
  b=np.random.choice(b,size=1)
  a1=a[0]
  b1=b[0]
  if matx[a1,b1]==-1:
    continue
  else:
    matx[a1,b1]=-1
    i=i+1
print(matx)

# M3
# listx1=[]
# for i in range(a):
#   for ii in range(b):
#     listx1.append([i,ii])
# listx2=[]
# for i in range(len(listx1)):
#   listx2.append(i)
# listx=list(np.random.choice(listx2,size=p,replace=False))
# for i in listx:
#   matx[tuple(listx1[i])]=-1
# print(f'after replacing\n {matx}')

main
 [[4 2 7 8]
 [6 0 5 3]
 [3 3 8 0]]


**Question 6. Create a 7*7 matrix with values 1,2,3,4,5,6 just below the diagonal**

Example:-1,2,3,4,5,6 should be below principal diagonal such as [[0 0 0 0 0 0 0] [1 0 0 0 0 0 0] [0 2 0 0 0 0 0] [0 0 3 0 0 0 0] [0 0 0 4 0 0 0] [0 0 0 0 5 0 0] [0 0 0 0 0 6 0]] 

In [ ]:
import numpy as np
matx=np.zeros((7,7))

for i in range(7):
 matx[i,i]=i
print(matx.astype('int64'))

[[0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 0 3 0 0 0]
 [0 0 0 0 4 0 0]
 [0 0 0 0 0 5 0]
 [0 0 0 0 0 0 6]]


**Question 7.create an array of interger of size 5*3. values in the array should be between 0 to 20. print subarray of array containing element (0,0),(0,1),(1,0),(1,1).**
Example:- if random generated array is [[1 2 3],[4 5 6],[7 8 9],[10 11 12],[13 14 15]] then program should print [[1 2],[4 5]]

In [ ]:
import numpy as np
a=np.random.randint(20,size=5*3).reshape(5,3)
#print('your matrix is\n',a)
#print('solution for your matrix is')
print('main\n',a)
print(a[0:2,0:2])

main
 [[ 3 17  6]
 [ 0 17 10]
 [ 0  9  0]
 [ 6 19  1]
 [ 6  0  9]]
[[ 3 17]
 [ 0 17]]


**Question 8. Create an 1-D array of size=8. Split array into three array of size 3,2,3 respectively.**
suppose 1-D array is [0 1 2 3 4 5 6 7] then print [0 1 2] [3 4] [5 6 7]

In [ ]:
import numpy as np
a=np.random.randint(10,size=8)
# print('your array is',a)
print(a[0:3])
print(a[3:5])
print(a[5:8])

[8 7 7]
[4 8]
[5 9 2]


**Question 9.Create a checkerboard 8x8 matrix using the tile function**
Example:- [[0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0] [0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0] [0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0] [0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0]]

In [ ]:
import numpy as np
a=np.array([[0,1],
           [1,0]])
b=np.tile(a,(4,4))
print(b)

# a=np.array([0,1,0,1,0,1,0,1])
# b=np.tile(a,9)
# i=0
# while i in range(len(b)-9):
#   print(b[i:i+9])
#   i=i+9

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Question 10. Create a matrix of ones of size(3*1) and a vector of size 3 . add created vector to every row of matrix.**
Hint:- broadcasting concept in numpy.

In [ ]:
import numpy as np
a=np.ones((3,1)).astype('int64')
b=np.random.randint(10,size=3)
print(f'another vector{b} \nand after adding vector to every row \n{a+b}')

another vector[0 6 9] 
and after adding vector to every row 
[[ 1  7 10]
 [ 1  7 10]
 [ 1  7 10]]


**Question 11. Create a list. Sort it with and without using numpy. Calculate time taken by both.**

In [ ]:
import time
a=[4,2,5,1,7,3,8,1,10,5]
b=np.array(a)

start1=time.time()
a.sort()
end1=time.time()

import numpy as np
start2=time.time()
b=np.sort(b)
end2=time.time()

print('without numpy\n',a,end1-start1)
print('with numpy\n',b,end2-start2)

without numpy
 [1, 1, 2, 3, 4, 5, 5, 7, 8, 10] 6.866455078125e-05
with numpy
 [ 1  1  2  3  4  5  5  7  8 10] 0.00012135505676269531


**Question 12. Create two matrices. Multipy two maritces with and without using numpy. Calculate time taken by both.**

In [ ]:
import time as t

mat1=[1,2,3,4,5]
mat2=[1,2,3,4,5]
matx1=np.array(mat1)
matx2=np.array(mat2)
start1=t.time()
a=[]
count=0
while count<len(mat1):
  a.append(mat1[count]*mat2[count])
  count=count+1
end1=t.time()

import numpy as np
start2=t.time()
# b=np.matmul(matx1,matx2)
b=matx1*matx2
end2=t.time()

print('without numpy\n',a,end1-start1)
print('with numpy\n',b,end2-start2)

**Question 13. Create a matrix. Find transpose, determinant and inverse(if possible) of the matrix.**

In [ ]:
import numpy as np

matx=np.random.randint(10,size=9).reshape(3,3)
print(f'your matrix is \n{matx}')

print('\ntranspose\n',matx.transpose())
print('\ndeterminant\n',np.linalg.det(matx))
print('\ninverse\n',np.linalg.inv(matx))

your matrix is 
[[0 5 6]
 [5 8 5]
 [5 5 4]]

transpose
 [[0 5 5]
 [5 8 5]
 [6 5 4]]

determinant
 -64.99999999999999

inverse
 [[-0.10769231 -0.15384615  0.35384615]
 [-0.07692308  0.46153846 -0.46153846]
 [ 0.23076923 -0.38461538  0.38461538]]


**Question 14. Create two matrix and check if they are equal.**

In [ ]:
import numpy as np

arr1=np.random.randint(10,size=9).reshape(3,3)
arr2=np.random.randint(10,size=9).reshape(3,3)
print(f'matrix1\n {arr1} \nand matrix2\n {arr2}')
# # for inputing our values
# arr1=np.array(list(map(int,input().split(' ')))).reshape(3,3)
# arr2=np.array(list(map(int,input().split(' ')))).reshape(3,3)
i=0
ii=0
count=0
while i<3:
  ii=0
  while ii<3:
    a=arr1[i,ii]==arr2[i,ii]
    if a==True:
      count=count+1
    ii=ii+1
  i=i+1
if count==9:
  print('True')
else:
  print('False')

matrix1
 [[7 0 2]
 [2 0 0]
 [3 7 4]] 
and matrix2
 [[3 9 6]
 [0 6 9]
 [0 6 0]]
False


**Question 15. Show example of reshape and resize on numpy array. Explain difference if any.**

In [ ]:

import numpy as np

print('1\nreshape is perticular it only shape and so cannot take more or less inputs')
print('on the other hand resize can accept all inputs it will remove(last eliment) or')
print('add (first eliment) accordingly;')

print('\nFor example')
print('now both will print the respective 3*3 matrix of size 9')
a=np.random.randint(10,size=9)
a=np.resize(a,(3,3))
b=np.random.randint(10,size=9).reshape(3,3)
print(f'for resize  3*3 matrix of size 9\n{a}\n for reshape  3*3 matrix of size 9\n{b}')

print('\nnow both will print the respective 3*3 matrix of size 10')
a=np.random.randint(10,size=10)
a=np.resize(a,(3,3))
print(f'for resize 3*3 matrix of size 10\n{a}')
try:
  b=np.random.randint(10,size=10).reshape(3,3)
  print(f'for reshape 3*3 matrix of size 10\n{b}')
except Exception as e:
  print(f'for reshape 3*3 matrix of size 10\n{e}')

print('\n2\nsecoundly, we need to define array which we need to resize and then shape or size')
print('and in reshape we have to write(.reshape) at the end of array that we are sorting')
print('which means we need to find the matrix and then reshape but')
print('in resize we can resize we only need name(variable) that we have asigned ')

1
reshape is perticular it only shape and so cannot take more or less inputs
on the other hand resize can accept all inputs it will remove(last eliment) or
add (first eliment) accordingly;

For example
now both will print the respective 3*3 matrix of size 9
for resize  3*3 matrix of size 9
[[5 1 7]
 [3 0 4]
 [2 3 7]]
 for reshape  3*3 matrix of size 9
[[1 6 1]
 [7 9 2]
 [7 3 3]]

now both will print the respective 3*3 matrix of size 10
for resize 3*3 matrix of size 10
[[5 8 5]
 [6 7 3]
 [5 8 3]]
for reshape 3*3 matrix of size 10
cannot reshape array of size 10 into shape (3,3)

2
secoundly, we need to define array which we need to resize and then shape or size
and in reshape we have to write(.reshape) at the end of array that we are sorting
which means we need to find the matrix and then reshape but
in resize we can resize we only need name(variable) that we have asigned 


**Question 16. Create matrix and print eigen values and eigen vector of it.**

In [ ]:
import numpy as np

mat=np.array([[1,2],[3,4]])
val,vector = np.linalg.eig(mat)
print(f'eigen values is \n{val}\n eigen vector is \n{vector}')

eigen values is 
[-0.37228132  5.37228132]
 eigen vector is 
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


**Question 17. Create matrix and print singular values and singular vector.** 

STEPS:

- Create a text file and write the following data in it.

```
 1  2  3
 4  5  6
 7  8  9
 10 11 12
```

- Read the text file to a numpy array
- Print the singular values 
- Print the singular vector

Hint- np.linalg.svd()





In [ ]:
import numpy as np
read = np.loadtxt('que 17.txt',dtype=int)
matx=np.array(read)
a,b,c=np.linalg.svd(matx)
print(f'read text file{read}\nsingular values{b}\n and {c}\nsingular vector{a}')

read text file[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
singular values[2.54624074e+01 1.29066168e+00 2.31173375e-15]
 and [[-0.50453315 -0.5745157  -0.64449826]
 [ 0.76077568  0.05714052 -0.64649464]
 [-0.40824829  0.81649658 -0.40824829]]
singular vector[[-0.14087668 -0.82471435  0.5377697  -0.1039411 ]
 [-0.34394629 -0.42626394 -0.63955314  0.539418  ]
 [-0.54701591 -0.02781353 -0.33420281 -0.7670127 ]
 [-0.75008553  0.37063688  0.43598625  0.3315358 ]]


from google.colab import drive
0ppiujoij
drive.mount('/content/drive')